// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("Cart")]
public partial class Cart
{
    [Key]
    public int CartID { get; set; }

    public int? UserID { get; set; }

    public int? ProductID { get; set; }

    public int? Quantity { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Carts")]
    public virtual Product Product { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("Carts")]
    public virtual User User { get; set; }
}