// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("Feedback")]
public partial class Feedback
{
    [Key]
    public int FeedbackID { get; set; }

    public int? UserID { get; set; }

    public int? ProductID { get; set; }

    public int? Rating { get; set; }

    [Column(TypeName = "text")]
    public string Comment { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Image { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateGiven { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Feedbacks")]
    public virtual Product Product { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("Feedbacks")]
    public virtual User User { get; set; }
}