// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("MembershipType")]
public partial class MembershipType
{
    [Key]
    public int MembershipTypeID { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string TypeName { get; set; }

    [Column(TypeName = "text")]
    public string Description { get; set; }

    [Column(TypeName = "text")]
    public string Benefits { get; set; }

    [InverseProperty("MembershipType")]
    public virtual ICollection<Membership> Memberships { get; set; } = new List<Membership>();
}