// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("Membership")]
public partial class Membership
{
    [Key]
    [Column("MembershipID")]
    public int MembershipId { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }

    [Column("MembershipTypeID")]
    public int? MembershipTypeId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Status { get; set; }

    [ForeignKey("MembershipTypeId")]
    [InverseProperty("Memberships")]
    public virtual MembershipType MembershipType { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Memberships")]
    public virtual User User { get; set; }
}