// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("MembershipType")]
public partial class MembershipType
{
    [Key]
    [Column("MembershipTypeID")]
    public int MembershipTypeId { get; set; }

    [StringLength(50)]
    public string MembershipTypeName { get; set; }

    [Column(TypeName = "ntext")]
    public string MembershipDescription { get; set; }

    [Column(TypeName = "ntext")]
    public string MembershipBenefits { get; set; }

    [InverseProperty("MembershipType")]
    public virtual ICollection<Membership> Memberships { get; set; } = new List<Membership>();
}