// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("Membership")]
public partial class Membership
{
    [Key]
    public int MembershipID { get; set; }

    public int? UserID { get; set; }

    public int? MembershipTypeID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string MembershipStatus { get; set; }

    [ForeignKey("MembershipTypeID")]
    [InverseProperty("Memberships")]
    public virtual MembershipType MembershipType { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("Memberships")]
    public virtual User User { get; set; }
}