// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("Payment")]
public partial class Payment
{
    [Key]
    [Column("PaymentID")]
    public int PaymentId { get; set; }

    [Column("OrderID")]
    public int? OrderId { get; set; }

    [Column("PaymentUserID")]
    public int? PaymentUserId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Amount { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PaymentMethod { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string PaymentStatus { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("Payments")]
    public virtual RentalOrder Order { get; set; }

    [ForeignKey("PaymentUserId")]
    [InverseProperty("Payments")]
    public virtual User PaymentUser { get; set; }
}