// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("Payment")]
public partial class Payment
{
    [Key]
    public int PaymentID { get; set; }

    public int? OrderID { get; set; }

    public int? PaymentUserID { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Amount { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string PaymentMethod { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string PaymentStatus { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("Payments")]
    public virtual RentalOrder Order { get; set; }

    [ForeignKey("PaymentUserID")]
    [InverseProperty("Payments")]
    public virtual User PaymentUser { get; set; }
}