// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("ProductDetail")]
public partial class ProductDetail
{
    [Key]
    [Column("ProductDetailID")]
    public int ProductDetailId { get; set; }

    [Column("ProductID")]
    public int? ProductId { get; set; }

    [Column("ColorID")]
    public int? ColorId { get; set; }

    [Column("SizeID")]
    public int? SizeId { get; set; }

    [Column("ImageID")]
    public int? ImageId { get; set; }

    [ForeignKey("ColorId")]
    [InverseProperty("ProductDetails")]
    public virtual Color Color { get; set; }

    [ForeignKey("ImageId")]
    [InverseProperty("ProductDetails")]
    public virtual Image Image { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductDetails")]
    public virtual Product Product { get; set; }

    [ForeignKey("SizeId")]
    [InverseProperty("ProductDetails")]
    public virtual Size Size { get; set; }
}