// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("Rating")]
public partial class Rating
{
    [Key]
    public int RatingID { get; set; }

    public int? UserID { get; set; }

    public int? ProductID { get; set; }

    [Column("Rating")]
    public int? Rating1 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateGiven { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Ratings")]
    public virtual Product Product { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("Ratings")]
    public virtual User User { get; set; }
}