// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("RentalOrder")]
public partial class RentalOrder
{
    [Key]
    public int OrderID { get; set; }

    public int? UserID { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string OrderStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DatePlaced { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DueDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReturnDate { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Total { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [InverseProperty("Order")]
    public virtual ICollection<RentalOrderDetail> RentalOrderDetails { get; set; } = new List<RentalOrderDetail>();

    [ForeignKey("UserID")]
    [InverseProperty("RentalOrders")]
    public virtual User User { get; set; }
}