// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

public partial class RentalOrderDetail
{
    [Key]
    public int OrderDetailsID { get; set; }

    public int? OrderID { get; set; }

    public int? ProductID { get; set; }

    public int? Quantity { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RentalStart { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RentalEnd { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("RentalOrderDetails")]
    public virtual RentalOrder Order { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("RentalOrderDetails")]
    public virtual Product Product { get; set; }
}